version: "3"
services:
  app:
    container_name: api-rest-node
    restart: always
    build: .
    ports:
      - "8000:8000"
    link:
      - mongo
    mongo:
      container_name: mongo
      image: mongo
      ports:
        - "27017:27017"